#!/bin/bash
#Made by @citz_id

source $HOME/.bashrc
sxhkd -c $HOME/.config/berry/sxhkdrc &

setxkbmap -layout us -variant altgr-intl

berryc top_gap 30

berryc border_width 0
berryc inner_border_width 5
berryc title_height 20

berryc focus_color 292d3e
berryc unfocus_color 292d3e
berryc inner_focus_color b89ca8
berryc inner_unfocus_color 343d41
berryc text_focus_color 2c3539
berryc text_unfocus_color 565679