#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty	desktop='^1' follow=on focus=on
bspc rule -a firefox	desktop='^2' follow=on focus=on
bspc rule -a thunar 	desktop='^3' follow=on focus=on
bspc rule -a geany 	desktop='^4' follow=on focus=on
bspc rule -a ncmpcpp 	desktop='^5' state=floating follow=on focus=on

#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
